/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as OrderRouteImport } from './routes/order'
import { Route as KhanaKhazanaRouteImport } from './routes/khana-khazana'
import { Route as HowToOrderRouteImport } from './routes/how-to-order'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CakesRouteImport } from './routes/cakes'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as RecipesSlugRouteImport } from './routes/recipes.$slug'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const KhanaKhazanaRoute = KhanaKhazanaRouteImport.update({
  id: '/khana-khazana',
  path: '/khana-khazana',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToOrderRoute = HowToOrderRouteImport.update({
  id: '/how-to-order',
  path: '/how-to-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CakesRoute = CakesRouteImport.update({
  id: '/cakes',
  path: '/cakes',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecipesRoute,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RecipesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cakes': typeof CakesRoute
  '/contact': typeof ContactRoute
  '/how-to-order': typeof HowToOrderRoute
  '/khana-khazana': typeof KhanaKhazanaRoute
  '/order': typeof OrderRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/shop': typeof ShopRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/recipes/': typeof RecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cakes': typeof CakesRoute
  '/contact': typeof ContactRoute
  '/how-to-order': typeof HowToOrderRoute
  '/khana-khazana': typeof KhanaKhazanaRoute
  '/order': typeof OrderRoute
  '/shop': typeof ShopRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/recipes': typeof RecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cakes': typeof CakesRoute
  '/contact': typeof ContactRoute
  '/how-to-order': typeof HowToOrderRoute
  '/khana-khazana': typeof KhanaKhazanaRoute
  '/order': typeof OrderRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/shop': typeof ShopRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/recipes/': typeof RecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cakes'
    | '/contact'
    | '/how-to-order'
    | '/khana-khazana'
    | '/order'
    | '/recipes'
    | '/shop'
    | '/recipes/$slug'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cakes'
    | '/contact'
    | '/how-to-order'
    | '/khana-khazana'
    | '/order'
    | '/shop'
    | '/recipes/$slug'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cakes'
    | '/contact'
    | '/how-to-order'
    | '/khana-khazana'
    | '/order'
    | '/recipes'
    | '/shop'
    | '/recipes/$slug'
    | '/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CakesRoute: typeof CakesRoute
  ContactRoute: typeof ContactRoute
  HowToOrderRoute: typeof HowToOrderRoute
  KhanaKhazanaRoute: typeof KhanaKhazanaRoute
  OrderRoute: typeof OrderRoute
  RecipesRoute: typeof RecipesRouteWithChildren
  ShopRoute: typeof ShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khana-khazana': {
      id: '/khana-khazana'
      path: '/khana-khazana'
      fullPath: '/khana-khazana'
      preLoaderRoute: typeof KhanaKhazanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-order': {
      id: '/how-to-order'
      path: '/how-to-order'
      fullPath: '/how-to-order'
      preLoaderRoute: typeof HowToOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cakes': {
      id: '/cakes'
      path: '/cakes'
      fullPath: '/cakes'
      preLoaderRoute: typeof CakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof RecipesRoute
    }
  }
}

interface RecipesRouteChildren {
  RecipesSlugRoute: typeof RecipesSlugRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
}

const RecipesRouteChildren: RecipesRouteChildren = {
  RecipesSlugRoute: RecipesSlugRoute,
  RecipesIndexRoute: RecipesIndexRoute,
}

const RecipesRouteWithChildren =
  RecipesRoute._addFileChildren(RecipesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CakesRoute: CakesRoute,
  ContactRoute: ContactRoute,
  HowToOrderRoute: HowToOrderRoute,
  KhanaKhazanaRoute: KhanaKhazanaRoute,
  OrderRoute: OrderRoute,
  RecipesRoute: RecipesRouteWithChildren,
  ShopRoute: ShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
